name: Swift

on: [push]

jobs:
  build:
    if: contains(github.event.head_commit.message, 'feat') || contains(github.event.head_commit.message, 'fix')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version
      - uses: actions/checkout@v4
      - name: Build
        run: swift build